[project]
name = "langgraph-basic"
version = "1.0.0"
description = "Langgraph basics"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=1.0.1",
    "langgraph-cli[inmem]>=0.4.4",
    "python-dotenv>=1.1.1",
]
