[project]
name = "langgraph-basics"
version = "1.0.0"
description = "Langgraph Basics"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=1.0.2",
    "langgraph-cli[inmem]>=0.4.4",
]
